// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8t09K-ZdoKZXxHOHx8aq2zb-S8V3tUFQ',
    appId: '1:898826305168:web:20cc10424c2fce3e762215',
    messagingSenderId: '898826305168',
    projectId: 'insta-clone-49eec',
    authDomain: 'insta-clone-49eec.firebaseapp.com',
    storageBucket: 'insta-clone-49eec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCboTqFe8mTMTy7W529CgJdQ_87cNcR-BE',
    appId: '1:898826305168:android:76b6e9cd107d12ba762215',
    messagingSenderId: '898826305168',
    projectId: 'insta-clone-49eec',
    storageBucket: 'insta-clone-49eec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGHuMxonaik34vyohz7Hf4mt_RYuqMZSE',
    appId: '1:898826305168:ios:1f94862af69b2b01762215',
    messagingSenderId: '898826305168',
    projectId: 'insta-clone-49eec',
    storageBucket: 'insta-clone-49eec.appspot.com',
    iosBundleId: 'com.example.instaClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGHuMxonaik34vyohz7Hf4mt_RYuqMZSE',
    appId: '1:898826305168:ios:3060cf4bd14c7760762215',
    messagingSenderId: '898826305168',
    projectId: 'insta-clone-49eec',
    storageBucket: 'insta-clone-49eec.appspot.com',
    iosBundleId: 'com.example.instaClone.RunnerTests',
  );
}
